/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorRegisterRouteImport } from './routes/vendor.register'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as DriverRegisterRouteImport } from './routes/driver.register'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRegisterRoute = VendorRegisterRouteImport.update({
  id: '/vendor/register',
  path: '/vendor/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRegisterRoute = DriverRegisterRouteImport.update({
  id: '/driver/register',
  path: '/driver/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/driver/register': typeof DriverRegisterRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/register': typeof VendorRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/driver/register': typeof DriverRegisterRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/register': typeof VendorRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/driver/register': typeof DriverRegisterRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/register': typeof VendorRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/shop'
    | '/track'
    | '/driver/register'
    | '/vendor/dashboard'
    | '/vendor/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/shop'
    | '/track'
    | '/driver/register'
    | '/vendor/dashboard'
    | '/vendor/register'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/shop'
    | '/track'
    | '/driver/register'
    | '/vendor/dashboard'
    | '/vendor/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ShopRoute: typeof ShopRoute
  TrackRoute: typeof TrackRoute
  DriverRegisterRoute: typeof DriverRegisterRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorRegisterRoute: typeof VendorRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/register': {
      id: '/vendor/register'
      path: '/vendor/register'
      fullPath: '/vendor/register'
      preLoaderRoute: typeof VendorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/register': {
      id: '/driver/register'
      path: '/driver/register'
      fullPath: '/driver/register'
      preLoaderRoute: typeof DriverRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ShopRoute: ShopRoute,
  TrackRoute: TrackRoute,
  DriverRegisterRoute: DriverRegisterRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorRegisterRoute: VendorRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
